FROM node:lts-slim as build

RUN mkdir -p /var/production/app
WORKDIR /var/production/app

COPY package.json .

RUN yarn install --silent

COPY . .

RUN yarn run build

EXPOSE 8080

ENV PORT 8080
ENV HOST 0.0.0.0

CMD ["yarn", "start"]

