FROM node:lts-slim as build

RUN mkdir -p /var/production/app
WORKDIR /var/production/app

COPY package.json .

RUN yarn install --silent

COPY . .

RUN yarn run build

FROM nginx:alpine

COPY ./http/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /var/production/app/build /usr/share/nginx/html

EXPOSE 8080

ENV PORT 8080
ENV HOST 0.0.0.0

CMD ["nginx", "-g", "daemon off;"]
