import Head from "next/head";

interface IRcpHeadProps {
  title: string
}

const RcpHead: React.FC<IRcpHeadProps> = ({ title }) => {
  return (
    <Head>
      <title>{title} - Ratchapol&apos;s Portfolio </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default RcpHead
